excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules:
  - line_length
  - file_length
  - function_body_length
  - unused_setter_value
type_body_length:
  - 400 # warning
  - 600 # error